name: GitHub Tiles
run-name: GitHub Tiles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  github-tiles:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tiles
        uses: mbwilding/github-tiles@main
