name: GitHub Tiles
run-name: GitHub Tiles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  github-tiles:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: GitHub Tiles
        uses: mbwilding/github-tiles@main
        with:
          token: ${{ secrets.TOKEN }}
